# -*- coding: utf-8 -*-
"""Datacleaning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EUEqASW6tyAJZpMqsKxoG7nx1em4rJY-
"""

import pandas as pd
import numpy as np
import time
import math
import datetime

df= pd.read_csv("Facilityraw.csv")

df.sort_values(by=["FACILITY_ID"])

TICKETS_FACILITY= df[["FACILITY_ID","TICKET_ID"]]

TICKETS_FACILITY

TICKETS_FACILITY.to_csv("TICKETS_FACILITY.csv", index= False)

df2= df[["FACILITY_ID","FACILITY_DESC","FACILITY_TYPE","FACILITY_CAPACITY","FACILITY_SUBTYPE","LOCATION","TIMESTAMP"]]

df2

df3= df2.drop_duplicates().reset_index(drop=True)

df3

df3= df2.drop_duplicates(subset=['FACILITY_ID'])

df3

df3.shape

df3.to_csv("Facility_norm.csv", index= False)

